config/routes.rb
Rails.application.routes.draw do
  resources :planes do
    patch :confirm_takeoff, on: :member
    patch :cancel, on: :member
    patch :takeoff, on: :member

    get :logs, on: :collection
  end

  get :stream, to: 'application#stream'

  root to: 'planes#index'
end

app/models/concerns/streamer.rb
class Streamer
  STREAM_CHANNEL = 'stream'

  def self.message(message)
    Redis.new.publish(STREAM_CHANNEL, message)
  end

  def self.message_state_changed(plane)
    "state_changed:#{plane.id}:#{plane.state}:#{plane.state.humanize}"
  end
end

app/models/log.rb
class Log < ActiveRecord::Base
  enum state: [
    :awaiting,
    :pending,
    :in_progress,
    :took_off
  ]

  enum event: [
    :state_changed,
    :plane_created,
    :plane_destroyed
  ]

  validates :state, allow_blank: true, inclusion: { in: states.keys }
  validates :event, inclusion: { in: events.keys }

  belongs_to :plane

  scope :ordered, -> { order(created_at: :desc) }
end

app/models/plane.rb
class Plane < ActiveRecord::Base
  before_update :before_update_validation, if: :state_changed?
  after_update  :on_update
  after_create  :on_create
  after_destroy :on_destroy

  has_secure_token

  enum state: [
    :awaiting,
    :pending,
    :in_progress,
    :took_off
  ]

  validates :number, length: { minimum: 3, maximum: 32 }, format: { with: /\A[\wа-яё]+\z/i }, uniqueness: true
  validates :state, inclusion: { in: states.keys }

  has_many :logs

  scope :ordered, -> { order(:number) }

  def takeoff
    unless awaiting?
      errors.add :base, I18n.t('plane.errors.already_in_progress')
      return false
    end

    self.state = self.class.in_progress.present? ? :pending : :in_progress
    save
  end

  def cancel
    unless in_progress? || pending?
      errors.add :base, I18n.t('plane.errors.cannot_cancel')
      return false
    end

    self.state = :awaiting
    save
  end

  def confirm_takeoff(token)
    unless in_progress?
      errors.add :base, I18n.t('plane.errors.not_in_progress')
      return false
    end

    unless self.token == token
      errors.add :base, I18n.t('plane.errors.invalid_credentials')
      return false
    end

    self.state = :took_off
    save
  end

  private

  def before_update_validation
    if state == 'in_progress' && self.class.in_progress.present?
      self.errors.add :base, I18n.t('plane.errors.in_progress_is_already_present')
      return false
    end

    self.state_changed_at = DateTime.now
  end

  def on_update
    if state_changed?
      Log.create plane: self, event: :state_changed, state: state
      Streamer.message(Streamer.message_state_changed(self))
      self.class.process_pending
    end
  end

  def on_create
    Log.create plane: self, event: :plane_created
  end

  def on_destroy
    Log.create plane: self, event: :plane_destroyed
    self.class.process_pending if in_progress?
  end

  def self.process_pending
    return if self.in_progress.present?

    pending_plane = self.pending.order(:state_changed_at).first

    if pending_plane
      pending_plane.in_progress!
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  include Tubesock::Hijack

  def stream
    hijack do |socket|
      handler = Thread.new do
        Redis.new.subscribe(Streamer::STREAM_CHANNEL) do |listener|
          listener.message do |_, data|
            socket.send_data(data)
          end
        end
      end

      socket.onclose { handler.kill }
    end
  end

  protected

  def render_message(type, text, options = {})
    available_types = %w(success info warning error)

    raise ArgumentError, 'unknown message type' unless available_types.include? type.to_s

    text ||= type.humanize

    render json: options.merge( { message_type: type, text: text } )
  end
end

app/controllers/planes_controller.rb
class PlanesController < ApplicationController
  before_action :find_plane, only: [:show, :destroy, :takeoff, :confirm_takeoff, :cancel]

  def index
    @planes = Plane.all.ordered
  end

  def create
    @plane = Plane.new allowed_params

    if @plane.save
      render_message :success, t('.success')
    else
      render_message :error, t('.error') + ': ' + @plane.errors[:number].join(', ')
    end
  end

  def destroy
    @plane.destroy
    redirect_to planes_path
  end

  def takeoff
    if @plane.takeoff
      render_message :success, t('planes.state.success')
    else
      render_message :error, "#{t('planes.state.error')}: #{@plane.errors[:base].join(', ')}"
    end
  end

  def cancel
    if @plane.cancel
      render_message :success, t('planes.state.success')
    else
      render_message :error, "#{t('planes.state.error')}: #{@plane.errors[:base].join(', ')}"
    end
  end

  def confirm_takeoff
    token = params[:token]

    if @plane.confirm_takeoff(token)
      render_message :success, t('planes.state.success')
    else
      render_message :error, "#{t('planes.state.error')}: #{@plane.errors[:base].join(', ')}"
    end
  end

  private

  def find_plane
    @plane = Plane.find(params[:id])
  end

  def allowed_params
    params.require(:plane).permit(:number)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def icon(icon)
    content_tag :i, nil, class: [:icon, icon]
  end
end

app/helpers/planes_helper.rb
module PlanesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RunwayControl</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="content">
    <div id="menu">
      <ul>
        <li><%= link_to 'Planes list', planes_path %></li>
        <li><%= link_to 'Log', logs_planes_path %></li>
      </ul>
    </div>

    <div id="logo">
      Runway <div class="right">Control</div>
    </div>

    <%= yield %>
  </div>
</body>
</html>

app/views/logs/_log.html.erb
<li><%= log.created_at %> - Plane #<%= log.plane_id %>: <%= log.event.humanize.downcase %>
  <%= "to #{log.state.humanize}" if log.state %></li>

app/views/planes/_plane.html.erb
<div class="plane" data-id="<%= plane.id %>" data-token="<%= plane.token %>">
  <div class="number"><%= link_to plane.number, plane_path(plane) %></div>
  <div class="state"><%= plane.state.humanize %></div>

  <div class="takeoff <%= 'hidden' unless plane.awaiting? %>">
    <%= link_to icon(:arrow_go), takeoff_plane_path(plane) %>
  </div>

  <div class="confirm <%= 'hidden' unless plane.in_progress? %>">
    <%= link_to icon(:check), confirm_takeoff_plane_path(plane) %>
  </div>

  <div class="cancel <%= 'hidden' unless plane.pending? || plane.in_progress? %>">
    <%= link_to icon(:cross), cancel_plane_path(plane) %>
  </div>

  <div class="remove">
    <%= link_to icon(:trash), plane_path(plane), method: :delete, data: { confirm: 'Are you sure?' } %>
  </div>
</div>

app/views/planes/index.html.erb
<div id="planes">
  <%= render @planes %>

  <div class="plane new">
    <div class="number">New plane</div>
    <div class="state">
      <%= form_for plane = Plane.new do |f| %>
        <%= f.text_field :number %>
      <% end %>
    </div>

    <div class="add">
      <%= link_to icon(:check), '#' %>
    </div>
  </div>

</div>

<script>init_planes_page();</script>

app/views/planes/logs.html.erb
<ul class="logs">
  <%= render Log.ordered %>
</ul>

app/views/planes/show.html.erb
<ul class="logs">
  <%= render @plane.logs.ordered %>
</ul>